datawarehouse:

  outputs:
    duckdb:
      type: duckdb
      path: ./database.duckdb
    mysql:
      type: mysql
      host: "{{ env_var('DB_HOST') }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      port: 3306
      schema: "{{ env_var('DB_DATABASE') }}"
      threads: 1
      ssl_disabled: True