AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  RawLayer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: producer
      Handler: script.handler
      Runtime: python3.10
      CodeUri: s3://code-ingestao-exe7/294aee1fa68f946f848161420fb4b2e1
      MemorySize: 128
      Role: arn:aws:iam::125892454700:role/LabRole
      Timeout: 15
      Environment:
        Variables:
          BUCKET_NAME: raw-inges-dados-123
          SQS_URL: https://sqs.us-east-1.amazonaws.com/125892454700/process
      Events:
        MyScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 12 * * ? *)
