AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  RawLayer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: trusted
      Handler: script.handler
      Runtime: python3.12
      CodeUri: trusted_function/
      MemorySize: 128
      Role: arn:aws:iam::924403880720:role/LabRole
      Timeout: 15
      Environment: 
        Variables:
          BUCKET_NAME: dados-exe6-trusted
      Events:
        MyScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 12 * * ? *)